#!/usr/bin/env bash
set -e
cd $(dirname $(dirname "${BASH_SOURCE[0]}"))
for m in "$@"; do
    echo ":::Python2:::"
    python2 -m test.test_$m
    echo ":::Python3:::"
    python3 -m test.test_$m
done
